const availableSuperpowers = [
    'Super Strength',
    'Flight',
    'Telekinesis',
    'Invisibility',
    'Teleportation',
    'Shape-Shifting',
    'Super Speed',
    'Super Intelligence',
    'X-ray Vision',
    'Time Travel',
    'Energy Projection',
    'Healing Factor',
    'Super Agility',
    'Super Durability',
    'Mind Control',
    'Weather Manipulation',
    'Elasticity',
    'Force Field Generation',
    'Underwater Breathing',
    'Immortality',
    'Elemental Manipulation',
    'Animal Communication',
    'Magnetism Manipulation',
    'Cloning',
    'Size Manipulation',
    'Time Manipulation',
    'Reality Warping',
];

export default availableSuperpowers;